// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadioServer.Data;

namespace RadioServer.Migrations.RadioDb
{
    [DbContext(typeof(RadioDbContext))]
    [Migration("20211105145728_scaffolding1")]
    partial class scaffolding1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RadioServer.Models.RadioStations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RadioStations");
                });
#pragma warning restore 612, 618
        }
    }
}
